# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auto deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g @quasar/cli
    - run: npm install
    - run: quasar build
    - name: Zip Release
    # You may pin to the exact commit or the version.
    # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
      uses: TheDoctor0/zip-release@0.6.2
      with:
        # Filename for archive
        filename: dist.tar.gz
        # Working directory before zipping
        path: ./dist 
        # Tool to use for archiving
        type: tar # optional, default is zip
    - name: HTTP Request Action
      # You may pin to the exact commit or the version.
      # uses: fjogeleit/http-request-action@f986377e36f4e3d86c0c42523e02b844785182e9
      uses: fjogeleit/http-request-action@v1.12.0
      with:
        # Request URL
        url: ${{ secrets.DEPLOY_UPLOAD_URL_GUITAR }}
        # Request Method
        method: POST
        # Content Type
        # contentType:  application/x-tgz # optional
        # Request Body as JSON String
        # data: # optional, default is {}
        # Map of absolute file paths as JSON String
        # files: '{dist:"./dist.tar.gz"}'
        # A single absolute file path
        file: ./dist.tar.gz # optional
        # Auth Username
        #username: # optional
        # Auth Password
        #password: # optional
        # Request Timeout in Sec
        timeout: 60000 # optional, default is 5000
        # Bearer Authentication Token
        # bearerToken: # optional
        # Custom HTTP Headers
        # customHeaders: # optional
        # Prevent this Action to fail if the request respond without an response
        #preventFailureOnNoResponse: # optional
        # Prevent this Action to fail if the request respond with one of the configured StatusCodes
        #ignoreStatusCodes: # optional
        # Escape newlines in data string content
        #escapeData: # optional
